# Generated by Django 6.0.2 on 2026-02-06 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojob',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='videojob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
