# Generated by Django 6.0.2 on 2026-02-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_generator', '0002_videojob_cancelled_alter_videojob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojob',
            name='segments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
